### ISSUE TITLE
Run should fail if an assertion fails

### ISSUE THREAD

**Issue by jyepesr1** [nareshnavinash/newman-run#1]
Since I'm running the script in a CI/CD environment I need to get feedback when some test fails, but I'm always getting exit 0, even when some assertion fails. I think it should fail with exit 1.

`function (err, summary) {
     if (err || summary.run.error || summary.run.failures.length) {
         process.exit(1);
     }
}`

**Comment by nareshnavinash** [comment]
This is making more sense. I will make the change and publish in the newer version

**Comment by nareshnavinash** [comment]
I have updated the changes and published them in version 1.2.2
Can you check and update here. Closing this issue, for now, feel free to reopen if needed.
