### ISSUE TITLE
ignore certificates while running with newman-run

### ISSUE THREAD

**Issue by ashlin-karkada** [nareshnavinash/newman-run#12]
how can I ignore certificates while running with newman-run? For newman it was the --insecure flag. However, this does not work for newman-ran. Can you help?

I am using the below command,
newman-run -f feed_file.json --insecure

**Comment by nareshnavinash** [comment]
@ashlin-karkada I need to take a look at this and get back to you on the compatibility 👍🏻

**Comment by Nielsvd94** [comment]
Is there any update on this functionality? At the moment I cannot use this package because --insecure is not supported.

**Comment by nareshnavinash** [comment]
I have added a hacky workaround to fix this, now you can use this package to hit insecure endpoints
