### ISSUE TITLE
Error while running multiple collection files

### ISSUE THREAD

**Issue by kishann92** [nareshnavinash/newman-run#13]
Observing an error while running multiple collection files in the feed file.
C:\Users\Wind\AppData\Roaming\npm\node_modules\newman-run\lib\core.js:75
                throw err;
                ^
null
[Issue_Screenshot.docx](https://github.com/nareshnavinash/newman-run/files/6566044/Issue_Screenshot.docx)

Attaching the project as zip file for reference

**Comment by nareshnavinash** [comment]
Hey @kishann92 `newman-run` is supported only in mac and linux environments for now. I need to add support for windows yet. Can you try with any ubuntu machines if possible?

**Comment by kishann92** [comment]
Hey Nareshnavinash,

Thanks for your quick response. Please let me know if there is any
information that can be received at a very basic level to run Newman for
multiple collections within a folder or multiple folders apart from writing
multiple lines.

Thanks
Kishan N

**Comment by nareshnavinash** [comment]
Without using newman-run I am unaware of it. Or you can try using any basic (node)[https://hub.docker.com/_/node] dockers and run the newman-run within that. If you could run in docker you can integrate this into CI systems seamlessly. I should be able to create that docker image if I get some time. But I cannot guarantee on the ETA.
