### ISSUE TITLE
code breaks if one collection completed the execution

### ISSUE THREAD

**Issue by ahnakhuda** [nareshnavinash/newman-run#15]
code breaks if one collection completed the execution.
┌─────────────────────────┬─────────────────────┬────────────────────┐
│                         │            executed │             failed │
├─────────────────────────┼─────────────────────┼────────────────────┤
│              iterations │                   1 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│                requests │                  23 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│            test-scripts │                  62 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│      prerequest-scripts │                  39 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│              assertions │                  61 │                  0 │
├─────────────────────────┴─────────────────────┴────────────────────┤
│ total run duration: 35.7s                                          │
├────────────────────────────────────────────────────────────────────┤
│ total data received: 4.54KB (approx)                               │
├────────────────────────────────────────────────────────────────────┤
│ average response time: 1457ms [min: 508ms, max: 2.5s, s.d.: 714ms] │
└────────────────────────────────────────────────────────────────────┘
#### Finished Execution ####

C:\Users\**********\AppData\Roaming\npm\node_modules\newman-run\lib\core.js:105
                throw err;
                ^
null
(Use `node --trace-uncaught ...` to show where the exception was thrown)

**Comment by raviahujauk** [comment]
Same error for me also.

**Comment by nareshnavinash** [comment]
Can you please use this in CI environment, If we run this in windows, we will get this errors, since the path formatting for windows is not yet supported.
