### ISSUE TITLE
If tests or assertions fail, Jenkins build shows as unstable instead of failed

### ISSUE THREAD

**Issue by not-ajay** [nareshnavinash/newman-run#25]
We are using this tool and integrated with Jenkins pipelines and we have this newman-run tests in the middle of our pipeline, so even if the tests or assertions fail, stage is considered as passed and moved on to the next stage and finally whole pipeline is shown as unstable.

@nareshnavinash Can you check if anything can be improved in this area ?

**Comment by nareshnavinash** [comment]
I have published a new version now. Can you pull and try with that and see if this issue is solved?

**Comment by not-ajay** [comment]
Yes it is working in version "1.3.2", much appreciated @nareshnavinash .
Closing.
