### ISSUE TITLE
Core.js returning an error when collection execution succeeded 

### ISSUE THREAD

**Issue by varayal** [nareshnavinash/newman-run#7]
I'm running latest newman-run version and when the collection execution succeeded we're getting this error pointing to the core.

```
#### Finished Execution ####

/Users/varaya/.nvm/versions/node/v14.6.0/lib/node_modules/newman-run/lib/core.js:69
                throw err;
                ^
null
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by AdamCKH** [comment]
I'm still getting the error:

Finished Execution
/Users/user/.nvm/versions/node/v12.16.3/lib/node_modules/newman-run/lib/core.js:75
throw err;
^
null
(Use node --trace-uncaught ... to show where the exception was thrown)

I have newman-run@1.2.4 and newman@5.2.4 and npm 6.14.4 installed.

**Comment by jasleenc117** [comment]
@nareshnavinash Can you please fix this as on Jenkins our builds are failing with this issue.
